// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXuAP7A9nlEC4tDt-14sjuexZ_Va5Sew',
    appId: '1:900466540912:web:726745902e1ac663028fb5',
    messagingSenderId: '900466540912',
    projectId: 'stressout-faf40',
    authDomain: 'stressout-faf40.firebaseapp.com',
    storageBucket: 'stressout-faf40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHTzKhrI_lR1S91Du86I9S9ZGE3JFglA',
    appId: '1:900466540912:android:0f5c42e5d9ed4491028fb5',
    messagingSenderId: '900466540912',
    projectId: 'stressout-faf40',
    storageBucket: 'stressout-faf40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQjgYzN37d2HDpy1AGQDoxtv5wYZNlU4',
    appId: '1:900466540912:ios:61c1b8d623efde35028fb5',
    messagingSenderId: '900466540912',
    projectId: 'stressout-faf40',
    storageBucket: 'stressout-faf40.appspot.com',
    iosClientId: '900466540912-ho6k7cbjr1kosjg46jj090v97d05r24s.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQjgYzN37d2HDpy1AGQDoxtv5wYZNlU4',
    appId: '1:900466540912:ios:c6761be438f198fb028fb5',
    messagingSenderId: '900466540912',
    projectId: 'stressout-faf40',
    storageBucket: 'stressout-faf40.appspot.com',
    iosClientId: '900466540912-6kjtgo9j8stgr30kh34doklsph342bjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressout.RunnerTests',
  );
}
